#!/bin/bash -e

prefix="$(realpath $(realpath $(which sdkmanager))/../../../..)"

if [[ $(arch 2> /dev/null) = arm64 ]]; then
    arch=arm64-v8a
    emulator=$prefix/emulator/emulator
else
    arch=x86_64
    emulator=$prefix/emulator-x86/emulator
fi

$emulator &> ~/.android/emulator.log \
    -avd mobiotsec \
    -no-boot-anim \
    -no-audio \
    -accel on -gpu swiftshader_indirect \
    &
echo $! > ~/.android/emulator.pid
